# Site settings
title: The Moviegoer
description: > # this means to ignore newlines until "baseurl:"
  The Moviegoer is Penn Cinema Initiative's movie blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pennmoviegoer.com" # the base hostname & protocol for your site
paginate: 5

# Build settings
markdown: kramdown
encoding: utf-8
