# Site settings
title: The Moviegoer
description: > # this means to ignore newlines until "baseurl:"
  The Moviegoer is Penn Cinema Initiative's movie blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://penncinemainitiative.github.io" # the base hostname & protocol for your site
paginate: 10

# Build settings
markdown: kramdown
